name: generic_reader_example

description:
  Demonstrates the usage of GenericReader.

version: 0.0.1

homepage: https://github.com/simphotonics/generic_reader

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: ^0.39.15
  ansicolor: ^1.0.2
  exception_templates: ^0.0.4
  generic_reader:
    path: ../
  meta: ^1.1.8
  source_gen: ^0.9.5

dev_dependencies:
  source_gen_test: ^0.1.1
  test: ^1.15.3
  pedantic: ^1.9.2
