name: example
description:
  Example demonstrating how to use the library generic_reader.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  generic_reader:
    path: ../
  source_gen: ^0.9.5
  source_gen_test: ^0.1.1
