name: generic_reader

description: Extension providing methods for the systematic reading of enums,
  constant lists, maps, sets, and generic compile-time constant expressions.

version: 0.4.1

homepage: https://github.com/simphotonics/generic_reader

topics:
  - analyzer
  - build
  - constant-expression
  - source_gen

environment:
  sdk: '^3.0.0'

dependencies:
  analyzer: ^7.0.0
  exception_templates: ^0.3.1
  source_gen: ^2.0.0

dev_dependencies:
  ansi_modifier: ^0.1.4
  lints: ^5.1.1
  source_gen_test: ^1.1.1
  test: ^1.25.14
  test_types:
    path: example/test_types
