name: generic_reader

description: Extension providing methods for the systematic reading of enums,
  constant lists, maps, sets, and generic compile-time constant expressions.

version: 0.4.0

homepage: https://github.com/simphotonics/generic_reader

environment:
  sdk: '^3.0.0'

dependencies:
  analyzer: ^6.2.0
  exception_templates: ^0.3.0
  source_gen: ^1.4.0

dev_dependencies:
  ansi_modifier: ^0.1.1
  lints: ^2.1.1
  source_gen_test: ^1.0.4
  test: ^1.24.6
  test_types:
    path: example/test_types
