name: generic_reader

description: Methods for the systematic reading of compile-time constant expressions.

version: 0.5.0

homepage: https://github.com/simphotonics/generic_reader

topics:
  - analyzer
  - build
  - constant-expression
  - source-generation

environment:
  sdk: '^3.9.0'

dependencies:
  analyzer: ^8.4.0
  exception_templates: ^0.3.2

dev_dependencies:
  ansi_modifier: ^0.1.5
  build_test: ^3.4.1
  lints: ^6.0.0
  test: ^1.26.3
