name: generic_reader

description: Enables retrieving generic const values from a static analyzer
  representation. Streamlines reading compile-time constants of type List, Map,
  Set, as well as Dart enums.

version: 0.2.0

homepage: https://github.com/simphotonics/generic_reader

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  exception_templates: ^0.2.0
  quiver: ^3.0.0
  source_gen: ^1.0.0

dev_dependencies:
  test_types:
    path: test/test_types
  ansicolor: ^2.0.1
  source_gen_test: ^1.0.0
  test: ^1.16.8
