name: generic_reader

description:
  Enables retrieving generic const values from a static analyzer representation.
  Streamlines reading constants of type List, Map, Set as well as Dart enums.

version: 0.1.2

homepage: https://github.com/simphotonics/generic_reader

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: ^0.39.10
  meta: ^1.2.2
  source_gen: ^0.9.5
  exception_templates: ^0.0.4

dev_dependencies:
  source_gen_test: ^0.1.1
  test: ^1.15.3
  generic_reader_example:
    path: example # Provides data-types used for testing purposes.
