name: generic_reader

description: Extension providing methods for the systematic reading of
  enums, constant lists, maps, sets, and generic compile-time constant expressions.

version: 0.3.1

homepage: https://github.com/simphotonics/generic_reader

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: '>=5.2.0 <7.0.0'
  exception_templates: ^0.2.4
  meta: ^1.9.0
  source_gen: any

dev_dependencies:
  ansicolor: ^2.0.1
  lints: ^2.0.1
  source_gen_test: ^1.0.4
  test: ^1.22.2
  test_types:
    path: example/test_types
