name: generic_reader

description: Extension on ConstantReader enabling the retrieval of generic
  compile-time constants. Streamlines reading constants of type List, Map, Set,
  as well as Dart Enums.

version: 0.3.0

homepage: https://github.com/simphotonics/generic_reader

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  exception_templates: ^0.2.4
  meta: ^1.9.0
  source_gen: ^1.2.7

dev_dependencies:
  ansicolor: ^2.0.1
  dartdoc: ^6.1.5
  lints: ^2.0.1
  source_gen_test: ^1.0.4
  test: ^1.22.2
  test_types:
    path: example/test_types
